### ISSUE TITLE
invalid upgrade.php file

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#1]
php end tag (?>) at the bottom of the file which is a blocker for approval.

other stuff like copyright header/gpl template also missing.

but... upgrade.php isn't a "required" file and it doesn't currently do anything - up to you if you want to fix the format of the file so it complies, or just delete it for now until you need it :-)

**Comment by naomiquirke** [comment]
I've turned upgrade.php into a stub, version 1.1

**Comment by naomiquirke** [comment]
I left the upgrade file as a stub, but added the copyright header/gpl template and removed the php end tag (?>).
Fixed version 1.1
