### ISSUE TITLE
user firstname + lastname instead of fullname() 

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#11]
https://github.com/naomiquirke/moodle-mod_cado/blob/master/classes/get_recipients_form.php#L59

should this be using fullname() ?

this isn't a blocker - just an fyi - feel free to close if you want to keep using firstname/lastname, but fullname takes care of the order of fields, and other internal settings required for different languages / organisations.

**Comment by naomiquirke** [comment]
OK I've updated, version 1.1
