### ISSUE TITLE
branch name documentation

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#12]
You have a few different branches in your github repo (master/ version 1.0/1.1) you might consider adding a block to your readme that explains which branch people should be using for which version of Moodle.

see an example here:
https://github.com/danmarsden/moodle-plagiarism_urkund#branches

Also it might be worth renaming your "master" branch - to "main" - there seems to be a general push to move away from using the term "master" which is the default git/github initial branch name. it's slightly easier to do this before other people start using your plugin.
https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/?amp=1

Various other links on the web about this too.

Here's what I've done to do this on my repos:
1) 
git checkout master
git checkout -b main
git push -u origin main

2) Edit all open pull requests and change the base branch from trying to merge with "master" to the new "main" branch (if you don't do this all the open pull requests will get closed on step 4 below.) - you don't have any pull requests, so you can ignore this step.

3) Change the "default" branch in github.
Click on the branches drop down and choose "view all branches" - then "change default branch" and set it to main.

4) Delete the old "master" branch by pressing the trash-can icon beside the master branch on the full branch list page.

**Comment by naomiquirke** [comment]
I've changed the default branch name to main as suggested, thanks
