### ISSUE TITLE
review compliance with guidelines

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#13]
the moodle.org plugins db has triggered a run through with the guidelines
see: 
https://moodle.org/plugins/pluginversion.php?id=21826

 might be worth going through this for informational purposes. (you don't have to fix them for approval in the plugins db.)

Most of these get picked up by travis (when travis is working.) - I think the only change you have to make in your travis config is in line 28/29 here:
https://github.com/naomiquirke/moodle-mod_cado/blob/master/.travis.yml#L28
change: "8.9" to "14.0"
take a look at my attendance one that is currently working:
https://github.com/danmarsden/moodle-mod_attendance/blob/main/.travis.yml

You can also run the same coding guideline tests locally by installing the following plugins:
https://moodle.org/plugins/local_codechecker
https://moodle.org/plugins/local_moodlecheck

and... there's a few diffferent ways to integrate these directly into your IDE of choice:
https://docs.moodle.org/dev/Linting#Linting_in_your_editor

**Comment by naomiquirke** [comment]
@danmarsden thanks a lot for all these tips. It would have taken ages to work that out myself.  I still can't get some of the linting to work in visual studio, eg the css, but I just edited it by hand based on the travis feedback.
I've now edited and run things through Travis and there are no errors.  I've uploaded the latest zip file to the Moodle plugins database.
