### ISSUE TITLE
unit test failure with code installed on 3.5 site

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#14]
With this plugin installed, when you run the core Moodle unit tests I'm seeing this error pop-up

I haven't looked closely, but I'm assuming it's a dumb test that expects nothing is configured to use airnotifier on fresh install - I'll run it through a 3.9 site unit tests to see if it's any better there later.
----------

There was 1 failure:

1) message_airnotifier_external_testcase::test_are_notification_preferences_configured
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     0 => Array (
-        'userid' => '198000'
-        'configured' => 0
+        'userid' => 198000
+        'configured' => 1

/var/www/html/message/output/airnotifier/tests/externallib_test.php:135
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit --colors "message_airnotifier_external_testcase" message/output/airnotifier/tests/externallib_test.php

**Comment by naomiquirke** [comment]
@danmarsden now that I've fixed the other errors, would you be able to rerun this as you commented?

**Comment by danmarsden** [comment]
yeah - that particular unit test failure isn't being triggered on a 3.9 site - lets just close this one off!
