### ISSUE TITLE
A little change

### ISSUE THREAD

**Issue by dinism** [naomiquirke/moodle-mod_cado#15]
When viewing CADO page (after approved)
![imagem](https://user-images.githubusercontent.com/14828021/103460223-7b638c80-4d0c-11eb-9883-0df39a61a8a4.png)

**Why not date after the comment?**
![imagem](https://user-images.githubusercontent.com/14828021/103460243-ac43c180-4d0c-11eb-8c91-4ead8ab139d8.png)
Thanks for the plugin. I'm a PT-PT translator. 100% done

**Comment by naomiquirke** [comment]
Thanks dinism for your interest. I will look into this.

**Comment by naomiquirke** [comment]
There is now a new version, [v2.1](https://github.com/naomiquirke/moodle-mod_cado/releases/tag/v2.1) addressing this.
This required there to be two edit boxes, one for the past comment and one for the current comment - which means that there are a now a couple more lines that need to be translated!
Thanks for your work, @dinism :)
