### ISSUE TITLE
Invalid get_string() identifier: 'modulename' or component 'cado'. Perhaps you are missing $string['modulename'] = ''; in mod/cado/lang/en/cado.php?

### ISSUE THREAD

**Issue by caiadogithub** [naomiquirke/moodle-mod_cado#16]
Moodle 3.11.7
PostgreSQL 12
PHP7.4

---------------

Invalid get_string() identifier: 'modulename' or component 'cado'. Perhaps you are missing $string['modulename'] = ''; in mod/cado/lang/en/cado.php?

    line 356 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7354 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 137 of /blocks/sharing_cart/lib/settingslib.php: call to get_string()
    line 40 of /blocks/sharing_cart/settings.php: call to admin_setting_configmulticheckboxmodtypes->__construct()
    line 122 of /lib/classes/plugininfo/block.php: call to include()
    line 81 of /admin/settings/plugins.php: call to core\plugininfo\block->load_settings()
    line 8927 of /lib/adminlib.php: call to require()
    line 19 of /admin/settings.php: call to admin_get_root()

**Comment by naomiquirke** [comment]
There is no missing $string['modulename'] = ''; in mod/cado/lang/en/cado.php.
