### ISSUE TITLE
Incorrect camel case

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#2]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by naomiquirke** [comment]
I've gone through the lang strings and double checked them.  Now the only non-sentence type strings remaining are used for natural titles which wouldn't make sense to remove.
Updated version 1.1
