### ISSUE TITLE
approve.php global calls

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#4]
https://github.com/naomiquirke/moodle-mod_cado/blob/master/approve.php#L27

require config.php sets up these vars automatically - you only need to use the global call if you are inside a function or class 

(this isn't a blocker for approval - just an fyi) :-)

**Comment by naomiquirke** [comment]
Thanks @danmarsden !
I really appreciate the pointers.
Fixed version 1.1
