### ISSUE TITLE
settings.php adds a require_once that doens't look needed

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#6]
https://github.com/naomiquirke/moodle-mod_cado/blob/master/settings.php#L30

I can't see an immediate reason for this - settings.php is also loaded in a lot of places, so if it doesn't have to include other libs it would be preferred. although mod/pluginname/lib.php is already included automatically in a lot of places too...

not a blocker for approval - just something worth checking at some point.

**Comment by naomiquirke** [comment]
Thanks, I've removed it now, and everything still seems to work.
It was just present in the settings file I initially copied from and I let sleeping dogs lie...
Updated version 1.1
