### ISSUE TITLE
cado.php get_notifiable_users undefined var $userid

### ISSUE THREAD

**Issue by danmarsden** [naomiquirke/moodle-mod_cado#9]
https://github.com/naomiquirke/moodle-mod_cado/blob/master/classes/cado.php#L726

I wonder if the function get_notifiable_users is actually called anywhere? - presume it was copied from elsewhere.

**Comment by naomiquirke** [comment]
I've removed that function, it was left over from some functionality that I plan to introduce in version 2, should it ever happen, to let an approver automatically message all course users upon an approval update.
Updated version 1.1.
